language: cpp
compiler:
  - clang
  - gcc

sudo: true

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -y
  - sudo apt-get install gcc-5 g++-5 clang-3.6 -y
  - sudo ln -fs /usr/bin/gcc-5 /usr/bin/gcc && sudo ln -fs /usr/bin/g++-5 /usr/bin/g++

install:
  - wget http://apt.biicode.com/install.sh && chmod +x install.sh && ./install.sh
  - bii --version
  - bii setup:cpp

before_script:
  - bii init . -L
  - bii find
  - bii configure

script:
  - bii build
  - ./bin/LB_json_test
