language: cpp
compiler:
  - clang
  - gcc

sudo: true

install:
  - wget http://apt.biicode.com/install.sh && chmod +x install.sh && ./install.sh
  - bii --version
  - bii setup:cpp

before_script:
  - bii init . -L

script:
  - bii find
  - bii configure
  - bii build
  - ./bin/LB_json_test
